apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: work-policy
spec:
  destination:
    name: work-server
  loadBalancing:
    name: LEAST_CONN
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxRequests: 1
      httpConsecutiveErrors: 5
      httpDetectionInterval: 10s
      sleepWindow: 30s
