apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: meeting-server-retry
spec:
  destination:
    name: meeting-server
  precedence: 10
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3
